pii_columns:
  date_of_birth:
    - "dob"
    - "birth_date"
    - "date_of_birth"
    - "birth_dt"
    - "dateofbirth"
    - "birth_day"
    - "bdate"
    - "birth_day"
  ssn:
    - "ssn"
    - "social_security_number"
    - "social_sec_num"
    - "soc_sec_num"
    - "social_sec"
    - "social_number"
  email:
    - "email"
    - "email_address"
    - "e_mail"
    - "mail_id"
    - "contact_email"
    - "emailaddr"
    - "eaddress"
  phone_number:
    - "phone"
    - "phone_number"
    - "contact_number"
    - "mobile"
    - "mobile_number"
    - "cell"
    - "cell_number"
    - "telephone"
    - "tel"
    - "contact"
  credit_card:
    - "credit_card"
    - "cc_number"
    - "card_number"
    - "creditcard"
    - "ccn"
    - "cardnum"
  account_number:
    - "account_number"
    - "acc_number"
    - "acct_num"
    - "bank_account"
    - "accountno"
    - "acc_no"
    - "iban"
    - "routing_number"
    - "acct"
    - "accountid"
